export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CREATE_ITEM = 'CREATE_ITEM';
export const GET_CATEGORIES = 'GET_CATEGORIES';
// export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORY_ITEMS = 'SET_CATEGORY_ITEMS';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const INCREMENT_CART_ITEM = 'INCREMENT_CART_ITEM';


